### ISSUE TITLE
License checker UX is bad in some Linux environments

### ISSUE THREAD

**Issue by enver-haase** [vaadin/testbench#1220] opened 2019-07-30 09:34 UTC
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.vaadin.enver.ui.ButtonIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.166 s <<< FAILURE! - in org.vaadin.enver.ui.ButtonIT
[ERROR] testButton(org.vaadin.enver.ui.ButtonIT)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:31)
        at com.vaadin.testbench.TestBenchTestCase.<clinit>(TestBenchTestCase.java:67)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
        at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
        at java.awt.Desktop.checkActionSupport(Desktop.java:221)
        at java.awt.Desktop.browse(Desktop.java:380)
        at com.vaadin.pro.licensechecker.SystemBrowser.open(SystemBrowser.java:16)
        at com.vaadin.pro.licensechecker.VaadinComIntegration.openBrowserAndWaitForKey(VaadinComIntegration.java:22)
        at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:56)
        at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:36)
        at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:29)

ehaase@ken-lnx:~/git/playground-personal/ceedeeeye$ java -version
java version "1.8.0_201"

System is Kubuntu 18.04LTS on x86_64.

        ... 25 more

**Comment by enver-haase** [comment] 2019-07-30 11:26
ehaase@ken-lnx:~/git/playground-personal/ceedeeeye$ ls -la /usr/bin/java
lrwxrwxrwx 1 root root 22 Apr 27  2017 /usr/bin/java -> /etc/alternatives/java
ehaase@ken-lnx:~/git/playground-personal/ceedeeeye$ ls -la /etc/alternatives/java
lrwxrwxrwx 1 root root 39 Jan 28  2019 /etc/alternatives/java -> /usr/lib/jvm/java-8-oracle/jre/bin/java

**Comment by tulioag** [comment] 2019-07-30 13:39
I am running Ubuntu 18.04, but I was unable to reproduce this, even removing the `~/.vaadin` directory. Which version of Testbench are you using? Do you have a project in which this error occurs I could take a look at?

**Comment by alvarezguille** [comment] 2019-07-30 14:35
We will investigate this further, in the meantime one possible workaround is to install the license key as described in the "Installing the license on a CI/build server" section of https://vaadin.com/pro/validate-license/subscription

**Comment by alvarezguille** [comment] 2019-08-13 12:15
UX should improve once https://github.com/vaadin/license-checker-vaadin10/pull/7 is merged and released
Now the exception is caught and error message with instructions is logged

**Closed by alvarezguille** 2019-08-13 12:15 UTC
