### ISSUE TITLE
Add support for ContextMenu

### ISSUE THREAD

**Issue by mvysny** [vaadin/testbench#1323] opened 2022-03-28 09:37 UTC
The `ContextMenuElement` class from `vaadin-context-menu-testbench-14.8.6.jar` is empty and does not offer any means of clicking on menu items. It would be great if the element would allow me to click a particular menu item (potentially nested within a submenu) with given ID.

**Comment by alvarezguille** [comment] 2022-03-28 10:56
Closing as duplicate of https://github.com/vaadin/flow-components/issues/1192

**Closed by alvarezguille** 2022-03-28 10:56 UTC
